// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
//
//! Emit `ServiceIndices.swift` from Anki's compiled `DescriptorPool`.
//!
//! The Swift FFI client (ios/ChargedUp/.../AnkiBridge.swift) calls the engine via
//! `anki_run_method(backend, service, method, ...)`. Those two u32s are Anki codegen
//! conventions, NOT anything SwiftProtobuf can derive from the messages, so we emit
//! them here — mirroring `rslib/proto_gen/src/lib.rs::get_services` +
//! `rslib/rust_interface.rs::render_top_level_run_method`:
//!
//!   * a **service** index is its positional index in the `DescriptorPool`
//!     (`ServiceDescriptor::index()`), and the client dispatches on the
//!     `Backend*Service` variants (the `run_service_method` match arms);
//!   * a **method** index is `MethodDescriptor::index()` within its backend service;
//!   * a collection-service method NOT present in the paired backend service is
//!     *delegated* onto the backend with index `col_method.index + backend_trait_len`
//!     (the `delegating_methods` offset). `BackendFrontendService` is skipped, exactly
//!     as the engine's dispatch does.
//!
//! Usage: service-index-dumper [DESCRIPTORS_BIN]
//!   (defaults to $DESCRIPTORS_BIN, else out/rslib/proto/descriptors.bin)

use std::collections::BTreeSet;

use anyhow::Context;
use anyhow::Result;
use prost_reflect::DescriptorPool;

fn main() -> Result<()> {
    let path = std::env::args()
        .nth(1)
        .or_else(|| std::env::var("DESCRIPTORS_BIN").ok())
        .unwrap_or_else(|| "out/rslib/proto/descriptors.bin".to_string());
    let bytes = std::fs::read(&path)
        .with_context(|| format!("reading descriptor set {path}; run `just check` first"))?;
    let pool = DescriptorPool::decode(bytes.as_ref())
        .with_context(|| format!("decoding DescriptorPool from {path}"))?;

    let services: Vec<_> = pool.services().collect();
    let mut out = String::new();
    out.push_str(HEADER);
    out.push_str("enum ServiceIndices {\n");

    for svc in &services {
        let name = svc.name();
        // The client dispatches on the Backend*Service variants only (see get_services'
        // partition_map). FrontendService is filtered from the dispatch, so skip it.
        if !name.starts_with("Backend") || name == "BackendFrontendService" {
            continue;
        }
        out.push_str(&format!("  enum {name} {{\n"));
        out.push_str(&format!(
            "    static let index: UInt32 = {}\n",
            svc.index()
        ));

        // trait methods: index() is the method's number within this backend service.
        let mut trait_names = BTreeSet::new();
        let mut trait_len = 0u32;
        for m in svc.methods() {
            trait_len += 1;
            trait_names.insert(m.name().to_string());
            out.push_str(&format!(
                "    static let {}: UInt32 = {}\n",
                lower_camel(m.name()),
                m.index()
            ));
        }

        // delegating methods: collection-service methods absent from the backend
        // service, offset by the number of backend trait methods.
        let col_name = name.trim_start_matches("Backend");
        if let Some(col) = services.iter().find(|s| s.name() == col_name) {
            for m in col.methods() {
                if !trait_names.contains(m.name()) {
                    let idx = m.index() as u32 + trait_len;
                    out.push_str(&format!(
                        "    static let {}: UInt32 = {}\n",
                        lower_camel(m.name()),
                        idx
                    ));
                }
            }
        }
        out.push_str("  }\n");
    }
    out.push_str("}\n");
    print!("{out}");
    Ok(())
}

/// Proto method names are PascalCase (e.g. `SyncLogin`, `GetQueuedCards`); Swift wants
/// lowerCamelCase (`syncLogin`, `getQueuedCards`). Lowercasing the first character is
/// sufficient and deterministic for these identifiers.
fn lower_camel(name: &str) -> String {
    let mut chars = name.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

const HEADER: &str = "// Copyright: Ankitects Pty Ltd and contributors\n\
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html\n\
//\n\
// GENERATED by scripts/service-index-dumper from Anki's DescriptorPool — DO NOT EDIT.\n\
// Regenerate with: scripts/generate_service_indices.sh\n\
//\n\
// These are the (service, method) u32 indices `anki_run_method` dispatches on. Because\n\
// Anki assigns them positionally (see rslib/rust_interface.rs), they MUST be derived\n\
// from the descriptor pool, never hand-guessed — appending an rpc shifts later indices.\n\n";
