// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html
//
// GENERATED by scripts/service-index-dumper from Anki's DescriptorPool — DO NOT EDIT.
// Regenerate with: scripts/generate_service_indices.sh
//
// These are the (service, method) u32 indices `anki_run_method` dispatches on. Because
// Anki assigns them positionally (see rslib/rust_interface.rs), they MUST be derived
// from the descriptor pool, never hand-guessed — appending an rpc shifts later indices.

enum ServiceIndices {
  enum BackendSyncService {
    static let index: UInt32 = 1
    static let syncMedia: UInt32 = 0
    static let abortMediaSync: UInt32 = 1
    static let mediaSyncStatus: UInt32 = 2
    static let syncLogin: UInt32 = 3
    static let syncStatus: UInt32 = 4
    static let syncCollection: UInt32 = 5
    static let fullUploadOrDownload: UInt32 = 6
    static let abortSync: UInt32 = 7
    static let setCustomCertificate: UInt32 = 8
  }
  enum BackendCollectionService {
    static let index: UInt32 = 3
    static let openCollection: UInt32 = 0
    static let closeCollection: UInt32 = 1
    static let createBackup: UInt32 = 2
    static let awaitBackupCompletion: UInt32 = 3
    static let latestProgress: UInt32 = 4
    static let setWantsAbort: UInt32 = 5
    static let checkDatabase: UInt32 = 6
    static let getUndoStatus: UInt32 = 7
    static let undo: UInt32 = 8
    static let redo: UInt32 = 9
    static let addCustomUndoEntry: UInt32 = 10
    static let mergeUndoEntries: UInt32 = 11
    static let setLoadBalancerEnabled: UInt32 = 14
    static let getCustomColours: UInt32 = 15
  }
  enum BackendCardsService {
    static let index: UInt32 = 5
    static let getCard: UInt32 = 0
    static let updateCards: UInt32 = 1
    static let removeCards: UInt32 = 2
    static let setDeck: UInt32 = 3
    static let setFlag: UInt32 = 4
  }
  enum BackendDecksService {
    static let index: UInt32 = 7
    static let newDeck: UInt32 = 0
    static let addDeck: UInt32 = 1
    static let addDeckLegacy: UInt32 = 2
    static let addOrUpdateDeckLegacy: UInt32 = 3
    static let deckTree: UInt32 = 4
    static let deckTreeLegacy: UInt32 = 5
    static let getAllDecksLegacy: UInt32 = 6
    static let getDeckIdByName: UInt32 = 7
    static let getDeck: UInt32 = 8
    static let updateDeck: UInt32 = 9
    static let updateDeckLegacy: UInt32 = 10
    static let setDeckCollapsed: UInt32 = 11
    static let getDeckLegacy: UInt32 = 12
    static let getDeckNames: UInt32 = 13
    static let getDeckAndChildNames: UInt32 = 14
    static let newDeckLegacy: UInt32 = 15
    static let removeDecks: UInt32 = 16
    static let reparentDecks: UInt32 = 17
    static let renameDeck: UInt32 = 18
    static let getOrCreateFilteredDeck: UInt32 = 19
    static let addOrUpdateFilteredDeck: UInt32 = 20
    static let filteredDeckOrderLabels: UInt32 = 21
    static let setCurrentDeck: UInt32 = 22
    static let getCurrentDeck: UInt32 = 23
  }
  enum BackendConfigService {
    static let index: UInt32 = 9
    static let getConfigJson: UInt32 = 0
    static let setConfigJson: UInt32 = 1
    static let setConfigJsonNoUndo: UInt32 = 2
    static let removeConfig: UInt32 = 3
    static let getAllConfig: UInt32 = 4
    static let getConfigBool: UInt32 = 5
    static let setConfigBool: UInt32 = 6
    static let getConfigString: UInt32 = 7
    static let setConfigString: UInt32 = 8
    static let getPreferences: UInt32 = 9
    static let setPreferences: UInt32 = 10
  }
  enum BackendDeckConfigService {
    static let index: UInt32 = 11
    static let addOrUpdateDeckConfigLegacy: UInt32 = 0
    static let getDeckConfig: UInt32 = 1
    static let allDeckConfigLegacy: UInt32 = 2
    static let getDeckConfigLegacy: UInt32 = 3
    static let newDeckConfigLegacy: UInt32 = 4
    static let removeDeckConfig: UInt32 = 5
    static let getDeckConfigsForUpdate: UInt32 = 6
    static let updateDeckConfigs: UInt32 = 7
    static let getIgnoredBeforeCount: UInt32 = 8
    static let getRetentionWorkload: UInt32 = 9
  }
  enum BackendSchedulerService {
    static let index: UInt32 = 13
    static let computeFsrsParamsFromItems: UInt32 = 0
    static let fsrsBenchmark: UInt32 = 1
    static let exportDataset: UInt32 = 2
    static let getQueuedCards: UInt32 = 3
    static let answerCard: UInt32 = 4
    static let schedTimingToday: UInt32 = 5
    static let studiedToday: UInt32 = 6
    static let studiedTodayMessage: UInt32 = 7
    static let updateStats: UInt32 = 8
    static let extendLimits: UInt32 = 9
    static let countsForDeckToday: UInt32 = 10
    static let congratsInfo: UInt32 = 11
    static let restoreBuriedAndSuspendedCards: UInt32 = 12
    static let unburyDeck: UInt32 = 13
    static let buryOrSuspendCards: UInt32 = 14
    static let emptyFilteredDeck: UInt32 = 15
    static let rebuildFilteredDeck: UInt32 = 16
    static let scheduleCardsAsNew: UInt32 = 17
    static let scheduleCardsAsNewDefaults: UInt32 = 18
    static let setDueDate: UInt32 = 19
    static let gradeNow: UInt32 = 20
    static let sortCards: UInt32 = 21
    static let sortDeck: UInt32 = 22
    static let getSchedulingStates: UInt32 = 23
    static let describeNextStates: UInt32 = 24
    static let stateIsLeech: UInt32 = 25
    static let upgradeScheduler: UInt32 = 26
    static let customStudy: UInt32 = 27
    static let customStudyDefaults: UInt32 = 28
    static let repositionDefaults: UInt32 = 29
    static let computeFsrsParams: UInt32 = 30
    static let getOptimalRetentionParameters: UInt32 = 31
    static let computeOptimalRetention: UInt32 = 32
    static let simulateFsrsReview: UInt32 = 33
    static let simulateFsrsWorkload: UInt32 = 34
    static let evaluateParams: UInt32 = 35
    static let evaluateParamsLegacy: UInt32 = 36
    static let computeMemoryState: UInt32 = 37
    static let fuzzDelta: UInt32 = 38
  }
  enum BackendAnkidroidService {
    static let index: UInt32 = 15
    static let schedTimingTodayLegacy: UInt32 = 0
    static let localMinutesWestLegacy: UInt32 = 1
    static let setPageSize: UInt32 = 2
    static let debugProduceError: UInt32 = 3
    static let runDbCommand: UInt32 = 4
    static let runDbCommandProto: UInt32 = 5
    static let insertForId: UInt32 = 6
    static let runDbCommandForRowCount: UInt32 = 7
    static let flushAllQueries: UInt32 = 8
    static let flushQuery: UInt32 = 9
    static let getNextResultPage: UInt32 = 10
    static let getColumnNamesFromQuery: UInt32 = 11
    static let getActiveSequenceNumbers: UInt32 = 12
  }
  enum BackendAnkiHubService {
    static let index: UInt32 = 17
    static let ankihubLogin: UInt32 = 0
    static let ankihubLogout: UInt32 = 1
  }
  enum BackendAnkiwebService {
    static let index: UInt32 = 19
    static let getAddonInfo: UInt32 = 0
    static let checkForUpdate: UInt32 = 1
  }
  enum BackendLinksService {
    static let index: UInt32 = 21
    static let helpPageLink: UInt32 = 0
  }
  enum BackendNotetypesService {
    static let index: UInt32 = 23
    static let addNotetype: UInt32 = 0
    static let updateNotetype: UInt32 = 1
    static let addNotetypeLegacy: UInt32 = 2
    static let updateNotetypeLegacy: UInt32 = 3
    static let addOrUpdateNotetype: UInt32 = 4
    static let getStockNotetypeLegacy: UInt32 = 5
    static let getNotetype: UInt32 = 6
    static let getNotetypeLegacy: UInt32 = 7
    static let getNotetypeNames: UInt32 = 8
    static let getNotetypeNamesAndCounts: UInt32 = 9
    static let getNotetypeIdByName: UInt32 = 10
    static let removeNotetype: UInt32 = 11
    static let getAuxNotetypeConfigKey: UInt32 = 12
    static let getAuxTemplateConfigKey: UInt32 = 13
    static let getChangeNotetypeInfo: UInt32 = 14
    static let changeNotetype: UInt32 = 15
    static let getFieldNames: UInt32 = 16
    static let restoreNotetypeToStock: UInt32 = 17
    static let getClozeFieldOrds: UInt32 = 18
  }
  enum BackendNotesService {
    static let index: UInt32 = 25
    static let newNote: UInt32 = 0
    static let addNote: UInt32 = 1
    static let addNotes: UInt32 = 2
    static let defaultsForAdding: UInt32 = 3
    static let defaultDeckForNotetype: UInt32 = 4
    static let updateNotes: UInt32 = 5
    static let getNote: UInt32 = 6
    static let removeNotes: UInt32 = 7
    static let clozeNumbersInNote: UInt32 = 8
    static let afterNoteUpdates: UInt32 = 9
    static let fieldNamesForNotes: UInt32 = 10
    static let noteFieldsCheck: UInt32 = 11
    static let cardsOfNote: UInt32 = 12
    static let getSingleNotetypeOfNotes: UInt32 = 13
  }
  enum BackendCardRenderingService {
    static let index: UInt32 = 27
    static let stripHtml: UInt32 = 0
    static let allTtsVoices: UInt32 = 1
    static let writeTtsStream: UInt32 = 2
    static let extractAvTags: UInt32 = 3
    static let extractLatex: UInt32 = 4
    static let getEmptyCards: UInt32 = 5
    static let renderExistingCard: UInt32 = 6
    static let renderUncommittedCard: UInt32 = 7
    static let renderUncommittedCardLegacy: UInt32 = 8
    static let stripAvTags: UInt32 = 9
    static let renderMarkdown: UInt32 = 10
    static let encodeIriPaths: UInt32 = 11
    static let decodeIriPaths: UInt32 = 12
    static let htmlToTextLine: UInt32 = 14
    static let compareAnswer: UInt32 = 15
    static let extractClozeForTyping: UInt32 = 16
  }
  enum BackendSearchService {
    static let index: UInt32 = 29
    static let buildSearchString: UInt32 = 0
    static let searchCards: UInt32 = 1
    static let searchNotes: UInt32 = 2
    static let joinSearchNodes: UInt32 = 3
    static let replaceSearchNode: UInt32 = 4
    static let findAndReplace: UInt32 = 5
    static let allBrowserColumns: UInt32 = 6
    static let browserRowForId: UInt32 = 7
    static let setActiveBrowserColumns: UInt32 = 8
  }
  enum BackendGithubService {
    static let index: UInt32 = 33
    static let getLatestRelease: UInt32 = 0
    static let downloadRelease: UInt32 = 1
  }
  enum BackendI18nService {
    static let index: UInt32 = 35
    static let translateString: UInt32 = 0
    static let formatTimespan: UInt32 = 1
    static let i18nResources: UInt32 = 2
  }
  enum BackendImageOcclusionService {
    static let index: UInt32 = 37
    static let getImageForOcclusion: UInt32 = 0
    static let getImageOcclusionNote: UInt32 = 1
    static let getImageOcclusionFields: UInt32 = 2
    static let addImageOcclusionNotetype: UInt32 = 3
    static let addImageOcclusionNote: UInt32 = 4
    static let updateImageOcclusionNote: UInt32 = 5
  }
  enum BackendImportExportService {
    static let index: UInt32 = 39
    static let importCollectionPackage: UInt32 = 0
    static let exportCollectionPackage: UInt32 = 1
    static let importAnkiPackage: UInt32 = 2
    static let getImportAnkiPackagePresets: UInt32 = 3
    static let exportAnkiPackage: UInt32 = 4
    static let getCsvMetadata: UInt32 = 5
    static let importCsv: UInt32 = 6
    static let exportNoteCsv: UInt32 = 7
    static let exportCardCsv: UInt32 = 8
    static let importJsonFile: UInt32 = 9
    static let importJsonString: UInt32 = 10
  }
  enum BackendMediaService {
    static let index: UInt32 = 41
    static let checkMedia: UInt32 = 0
    static let addMediaFile: UInt32 = 1
    static let trashMediaFiles: UInt32 = 2
    static let emptyTrash: UInt32 = 3
    static let restoreTrash: UInt32 = 4
    static let extractStaticMediaFiles: UInt32 = 5
  }
  enum BackendStatsService {
    static let index: UInt32 = 43
    static let cardStats: UInt32 = 0
    static let getReviewLogs: UInt32 = 1
    static let graphs: UInt32 = 2
    static let getGraphPreferences: UInt32 = 3
    static let setGraphPreferences: UInt32 = 4
    static let masteryQuery: UInt32 = 5
  }
  enum BackendTagsService {
    static let index: UInt32 = 45
    static let clearUnusedTags: UInt32 = 0
    static let allTags: UInt32 = 1
    static let removeTags: UInt32 = 2
    static let setTagCollapsed: UInt32 = 3
    static let tagTree: UInt32 = 4
    static let reparentTags: UInt32 = 5
    static let renameTags: UInt32 = 6
    static let addNoteTags: UInt32 = 7
    static let removeNoteTags: UInt32 = 8
    static let findAndReplaceTag: UInt32 = 9
    static let completeTag: UInt32 = 10
  }
}
